### ISSUE TITLE
How to bind to dictionary

### ISSUE THREAD

**Issue by edwardsayer** [daliwali/simulacra#65]
How to bind to dictionary? for example, given:
```js
sex: {
     edward: 'male',
     nancy: 'female'
}
```
how to render as:
```
| name   | sex    |
| ------ | ------ |
| edward | male   |
| nancy  | female |
```

**Comment by daliwali** [comment]
Short answer is you can't, because that introduces unsolvable problems about re-ordering keys on objects.

An approach that will work is converting the data to an array:

```js
[
  { name: 'edward', sex: 'male' },
  { name: 'nancy', sex: 'female' }
]
```

Had the data been a dictionary, you can't re-order the keys without constantly rewriting the dictionary (i.e. try moving "nancy" to index zero). Just use the right data structure for the job.

**Comment by edwardsayer** [comment]
Got it. Thanks for your reply. :)
